# Generated by Django 5.2.17 on 2026-09-18 11:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('public_transit', 'Public Transit'), ('electric_vehicle', 'Electric Vehicle'), ('driving_car', 'Driving / Car')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_emission_factor_g_per_km', models.DecimalField(decimal_places=3, help_text='Default emission factor in g CO2 per passenger-km.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_label', models.CharField(blank=True, max_length=255)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_label', models.CharField(blank=True, max_length=255)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carbon_saved_g', models.DecimalField(blank=True, decimal_places=3, help_text='Calculated carbon savings in grams CO2. Populated by later-phase logic.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('integrity_hash', models.CharField(blank=True, help_text='SHA-256 hex digest, populated on journey finalization by a later phase.', max_length=64)),
                ('legal_disclaimer_accepted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
                ('transport_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journeys', to='core.transportmode')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AchievementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('points_earned', 'Points Earned'), ('streak_milestone', 'Streak Milestone'), ('badge_unlocked', 'Badge Unlocked')], max_length=32)),
                ('points', models.IntegerField(default=0)),
                ('badge_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_logs', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, help_text='Journey that triggered this entry, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_logs', to='core.journey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_factor_g_per_km', models.DecimalField(decimal_places=3, help_text='Emission factor value as it stood at capture time.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission_snapshot', to='core.journey')),
                ('transport_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_snapshots', to='core.transportmode')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_transport_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.transportmode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.journey')),
            ],
            options={
                'ordering': ['journey', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('journey', 'sequence'), name='unique_journey_point_sequence')],
            },
        ),
    ]
